CHANGELOG.md, README.md, echo/sentryecho.go, example/fasthttp/main.go, fasthttp/README.md, fasthttp/sentryfasthttp.go, gin/sentrygin.go, http/sentryhttp.go, iris/sentryiris.go, martini/sentrymartini.go, negroni/sentrynegroni.go
TODO: Add to Docs once merged.
=> feat: New fasthttp integration

client.go
=> Change SampleRate type to float64

.travis.yml
follow up #145 to extract `sudo` change.
=> ci: drop outdated sudo

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This can help us guide users when creating new issues.
=> misc: Add issue templates

.github/pull_request_template.md, CONTRIBUTING.md
The objective is to help potential contributors and project maintainers
by having some clearly communicated guidelines, while still being low
barrier to entry for simple contributions.
=> misc: Add Pull Request guidance

hub.go
=> fix: Synchronize access and mutation of Hub.lastEventID

stacktrace.go, stacktrace_external_test.go, stacktrace_test.go
=> feat: Extract stack frames from golang.org/x/xerrors

http/sentryhttp.go
=> doc: Improve documentation of sentryhttp package

sentry.go
=> Fix PushPushScope in doc

http/sentryhttp.go
=> Simplify initialisation of sentry http

echo/sentryecho.go, fasthttp/sentryfasthttp.go, gin/sentrygin.go, http/sentryhttp.go, iris/sentryiris.go, martini/sentrymartini.go, negroni/sentrynegroni.go
Follow-up on #292 to keep all implementations similar.
=> ref: Simplify and uniformize sentry*.New functions

client.go, client_test.go
For readability and testability. Also expand the comment/justification for the current behavior.
=> ref: Extract event sampling to a function

client_test.go
=> Minor test improvements

.craft.yml
So it can pick up unreleased section
=> ci: Change changelogPolicy to auto

.github/workflows/stale.yml
This PR adds a stale bot to dismiss stale issues and pull requests
=> feat(ci): add stale bot

dynamic_sampling_context_test.go, interfaces.go, tracing.go, tracing_test.go, transport.go
This adds `TransactionInfo` to the Event.
=> [Dynamic Sampling] TransactionInfo

README.md
=> docs: Fixed broken links

Makefile
...otherwise some nested packages are not tested.
=> fix(test): Run test with coverage for all packages in a module

.codecov.yml
Just some basic quality-of-life improvements.
Config file reference: https://docs.codecov.com/docs/codecovyml-reference
=> test: Add Codecov configuration file

CHANGELOG.md
=> doc: Prepare 0.18.0

otel/go.sum
We'll need to run this for all submodules in CI, will be done in a separate task.
=> fix(build): Tidy otel submodule

CHANGELOG.md
We're aiming to release this early next week.
=> doc: Prepare 0.19.0 release

otel/span_processor.go
=> Steven is a Go contributor

_examples/http/main.go
Closes https://github.com/getsentry/sentry-go/issues/620
=> fix: Update _examples/http

tracing.go
I was adding Sentry tracing to our project and found a small typo. Figured I would fix it up quick!
=> doc: fix typo in ToSentryTrace

http/sentryhttp.go
=> fix: sentryhttp - correct SDK identifier in comments

.craft.yml, .github/workflows/danger.yml, CHANGELOG.md
=> ci: add the common Danger workflow

go.mod, go.sum
Reverts getsentry/sentry-go#820
=> Revert "build(deps): bump golang.org/x/net from 0.21.0 to 0.23.0"

slog/README.MD
=> fix: use correct Go import for slog package

_examples/slog/main.go
=> fix: remove dsn from slog example

echo/sentryecho.go, fasthttp/sentryfasthttp.go, fiber/sentryfiber.go, gin/sentrygin.go, http/sentryhttp.go, iris/sentryiris.go, logrus/logrusentry.go, negroni/sentrynegroni.go
Fixing typos and adding some comments ...
=> Fix typos / add comments for integrations

logrus/logrusentry.go, logrus/logrusentry_test.go
=> handle sentry.Request properly in sentrylogrus

tracing.go, tracing_test.go
=> update the DSC sample rate based on client options

.github/workflows/lint.yml, .golangci.yml, client_test.go, internal/httputils/wrap_writer.go, internal/ratelimit/category_test.go, transport.go, util.go
=> Update golangci-lint to v2

CHANGELOG.md
=> Prepare 0.33.0

log.go, log_test.go
ref https://github.com/getsentry/sentry-docs/pull/13974
=> fix(logs): Don't gate user behind `SendDefaultPII`

batch_logger.go, client.go, log_test.go
Hotfix for flush only being able to be called once.
=> Allow flush to be used multiple times
