- .travis.yml
- api.go
- client.go
- dsn.go
- dsn_test.go
- examples/basic/main.go
- examples/http/main.go
- go.mod
- go.sum
- hub.go
- integrations/environment.go
- integrations/request.go
- mocks_test.go
- stacktrace_test.go
- transport.go
- transport_test.go
- util.go
What default transport should be able to do:
- DONE: queue events delivery
- DONE: drop events after queue is filled (30 requests)
- DONE: allow for knowing when everything was sent (`flush`)
- DONE: blocks the queue when server returns `429` using `Retry-After` header or 60sec default
- DONE: allow for configuring proxy and custom ssl certificated
- DONE: log to a debugger when server responds with error
> feat: Transport implementation

- .craft.yml
- scripts/craft-pre-release.sh
- sentry.go
Bumping that "Version" in `sentry.go` is probably a job for Craft.
Should also take care of https://github.com/getsentry/sentry-go/issues/17
> build: Bump version when releasing with Craft

- hub.go
- hub_test.go
Otherwise, we get a segfault at https://github.com/getsentry/sentry-go/blob/master/hub.go#L184 when Client is not initialized (e.g., empty DSN)
> fix: Check for initialized Client in AddBreadcrumbs

- CHANGELOG.md
- scope.go
- scope_test.go
Fixes https://github.com/getsentry/sentry-go/issues/21
cc: @mattcollum
> fix: Use NewScope instead of literal struct inside a scope.Clear call

- transport.go
Fixes https://github.com/getsentry/sentry-go/issues/23
> fix: Add to WaitGroup before the request is put inside a buffer

- stacktrace.go
This allows us to read files content for multi-package apps deployed to AWS Lambda with
```
$ GOOS=linux go build main.go && zip -r handler.zip *
```
> feat: Better source code location resolution and more useful inapp frames

- CHANGELOG.md
- transport.go
- transport_test.go
Fixes https://github.com/getsentry/sentry-go/issues/44
> fix: Retry event marshalling without contextual data if the first pass fails

- dsn.go
Go 1.11.13 and 1.12.8 received backported fixes for security issues with
url.Parse. One of the fixes includes stricter port validation.
With those minor versions of Go running in Travis,
TestInvalidDsnInvalidPort fails because url.Parse returns an error when
it previously didn't, thus NewDsn returns &DsnParseError{"invalid url"}
instead of &DsnParseError{"invalid port"}.
Including the error from url.Parse in the message both provides more
context for SDK users to understand why their DSN string was refused,
and fixes the test because "invalid port" is part of the now included
error message from url.Parse.
For reference, the backports are:
- https://github.com/golang/go/issues/33632
- https://github.com/golang/go/issues/33633
> fix: Include url.Parse error in DsnParseError

- stacktrace.go
- stacktrace_test.go
It is unnecessary to compile the same regexps over and over with every
call to `filterFrames`.
This improves the performance of `NewStacktrace()` reducing both CPU time
and memory allocation.
```
$ go1.11.13 test -run=- -count=5 -bench=. -benchmem | tee old.txt
$ # make changes ...
$ go1.11.13 test -run=- -count=5 -bench=. -benchmem | tee new.txt
$ benchstat old.txt new.txt
name             old time/op    new time/op    delta
NewStacktrace-8    54.0µs ± 0%    12.6µs ± 1%  -76.73%  (p=0.008 n=5+5)
name             old alloc/op   new alloc/op   delta
NewStacktrace-8    92.1kB ± 0%     7.3kB ± 0%  -92.08%  (p=0.008 n=5+5)
name             old allocs/op  new allocs/op  delta
NewStacktrace-8      92.0 ± 0%      15.0 ± 0%  -83.70%  (p=0.008 n=5+5)
```
> misc: Compile regexps only once

- hub.go
- hub_test.go
- mocks_test.go
This builds upon #36 to make Hub safe for use from multiple goroutines.
- Test concurrent changes to `Hub.stack`;
- Remove `RWMutex` from Hub's exported API;
- Test and fix concurrent changes to `layer.client`.
> Improve Hub concurrent use safety

- integrations.go
- integrations_test.go
Fixes https://github.com/getsentry/sentry-go/issues/55
> fix: Make sure that cache is locked when updating for contextifyFramesIntegration

- integrations.go
NewEvent() doesn't return Modules as nil, which was preventing this integration from working.
The extra flag was added to prevent repeatedly trying to cache the modules if getModules() returned nil.
> Fix module integration

- integrations.go
Adds information discussed in https://github.com/getsentry/sentry-go/issues/74
> Send extra information exposed by the Go runtime

- .travis.yml
This prevents introducing new dependencies without a proper update to
go.mod, and also fails the Travis build in the presence of extraneous
dependencies in go.mod after e.g. an old dependency gets removed.
From `go help modules`:
> The -mod build flag provides additional control over updating and use of go.mod.
>
> If invoked with -mod=readonly, the go command is disallowed from the implicit
> automatic updating of go.mod described above. Instead, it fails when any changes
> to go.mod are needed. This setting is most useful to check that go.mod does
> not need updates, such as in a continuous integration and testing system.
> The "go get" command remains permitted to update go.mod even with -mod=readonly,
> and the "go mod" commands do not take the -mod flag (or any other build flags).
> Ensure go.mod is up-to-date via Travis CI

- client.go
- client_test.go
* to avoid nil reference
* it's a bit bothering to pass it when using client directly
> accept nil EventModifier

- gin/sentrygin.go
Fixes https://github.com/getsentry/sentry-go/issues/69
cc @macklin-10x
> feat: Check for broken pipe errors in Gin integration

- client.go
- client_test.go
Fixes https://github.com/getsentry/sentry-go/issues/70 cc @mfridman @fedoricobond
> feat: Extract correct type and value from top-most error

- client.go
- transport.go
Closes https://github.com/getsentry/sentry-go/issues/62
TODO: Update docs.sentry.io
> feat: Add HTTPClient option

- interfaces.go
- stacktrace.go
Each exposed struct has a link to the docs that lead to a 404.
> docs: Update links to event-playloads

- README.md
The Slack channel was archived and replaced with Discord.
This change complements the existing Discord badge.
> docs: Replace Slack with Discord

- example/with_extra/main.go
Fixes build failures triggered by 'line length linter'.
Shorter lines are easier to read.
> docs(example): Reflow long comment lines

- dsn.go
- dsn_test.go
Port of a [feature from the JavaScript SDK](https://github.com/getsentry/sentry-javascript/blob/645ff532941d9a23bb6531c6305e99544b356502/packages/core/src/api.ts#L48) which supports DSNs with a
custom path prefix (e.g. http://user@host/prefixed/42).
> Add support for path prefixes in the DSN

- integrations.go
Use local struct fields instead of globals.
Ensure modules cache is filled only once and safe for concurrent use
using sync.Once.
Fixes #104
> fix: Eliminate data race in modules integration

- go.mod
Currently the go tool use the Go version defined in go.mod to check for
uses of features that did not exist prior to the specified version.
Additionally, when a build fails, that version may end up in the error
message.
To prevent confusion for SDK users, set the version to the oldest Go
release supported by sentry-go.
Fixes #83
> build: Reset go.mod version to 1.11

- interfaces.go
- interfaces_test.go
fix: request body logging [#84]
> fix: request body logging [#84]

- hub.go
- hub_test.go
- sentry.go
Fixes https://github.com/getsentry/sentry-go/issues/98
I know it requires a change in `Hub` struct and `LastEventID` signature, but this method was never implemented in the first place and we are still in `0.x` so I think it should be fine.
> fix: Correctly store last event id

- go.mod
- go.sum
Require github.com/ugorji/go@v1.1.7 or later.
This is a dependency coming from github.com/gin-gonic/gin that had a
problem with conflicting multiple Go modules in a single Git repository.
Version 1.1.7 fixed the issue. The latest version
github.com/gin-gonic/gin@v1.5.0 requires github.com/ugorji/go@v1.1.7.
Since gin@v1.5.0 also introduces a breaking change, we can help our
users without requiring them to move on to gin@v1.5.0 right now.
Fixes #87
> build: Require github.com/ugorji/go@v1.1.7

- dsn.go
- sentry.go
Document what "7" means with an (unexported) constant.
Though unexported, the constant is of type string to accommodate possible future values that would not be a good fit for an int/number, e.g. "8.0".
> ref: extract magic number into a constant

- client.go
- hub.go
- sourcereader_test.go
- stacktrace.go
- util.go
From https://github.com/golangci/golangci-lint#nolint
> Use //nolint instead of // nolint because machine-readable comments
> should have no space by Go convention.
> style: Use '//nolint' when disabling linters

- dsn_test.go
- go.mod
- go.sum
- Use cmp.Diff to compare values and print easy to read diffs on error.
- Use table tests to consistently check the same things for multiple
inputs. Previously, some tests omitted parts that were covered by
others.
- Use consistent names and values matching DSN concepts. Helps with
reading and understanding tests.
- Use raw strings to avoid escaping quotes.
- Do not ignore errors from NewDsn.
> test: Overhaul DSN tests

- .travis.yml
The current recommended installation steps use githubusercontent.com
instead of goreleaser.com.
Additionally, pin to a specific tagged version of the install script to
ensure reproducible installations of the tool.
Use latest available version 1.21.0.
> ci(travis): Bump golangci-lint version

- .travis.yml
- Test against go@master to help us verify if the SDK will work with a
new Go release before the release is shipped. Failed builds are allowed,
i.e., they do not block PRs.
- Test with GO111MODULE=off and GO111MODULE=on, as our users could be
using Go Modules or not.
- Test code outside of GOPATH. It should be okay to work on sentry-go
either inside or outside of GOPATH (Module mode). *Temporarily* marked
to allow failures. This reproduces #100 in our CI environment.
Build matrix increases from 3 jobs to 2*4+1 = 9 jobs.
> ci(travis): Test more env and Go combinations

- .golangci.yml
- .travis.yml
- integrations_test.go
- stacktrace.go
- stacktrace_external_test.go
- stacktrace_test.go
> fix(stacktrace): Do not rely on AbsPath for filtering

- stacktrace.go
- stacktrace_external_test.go
- stacktrace_test.go
The frame.Module field in its current form may contain entries like:
github.com/getsentry/sentry-go.(*Hub)
github.com/getsentry/sentry-go.(*Client)
github.com/getsentry/sentry-go.(*Client)
Taking those into account now.
Fixes up #123.
> fix(stacktrace): Filter out internal SDK methods

- stacktrace.go
- stacktrace_test.go
Makes function receivers part of the function name and not part of the package name.
Add tests and fix `filteredFrames` to ensure it ignores all packages related to the SDK.
Fixes #126.
> fix(stacktrace): Correctly report package names and ignore subpackages

- .golangci.yml
- hub_test.go
Temporarily binding the hub client to nil introduces the (unintended)
possibility of dropping events, as Hub.CaptureMessage and related
methods bail when their client is nil.
It was possible to reproduce the issue by running the tests many times
in a row with a command like:
go test -race -count 500 -failfast -run TestConcurrentHubClone
Fixes #132
> Fix TestConcurrentHubClone

- transport.go
- transport_test.go
Rewrite HTTPTransport internals to remove a data race and occasional
panics.
Prior to this, HTTPTransport used a `sync.WaitGroup` to track how many
in-flight requests existed, and `Flush` waited until the observed number
of in-flight requests reached zero.
Unsynchronized access to the WaitGroup lead to panics (reuse before
wg.Wait returns) and data races (undefined order of wg.Add and wg.Wait
calls). See https://github.com/getsentry/sentry-go/issues/103#issuecomment-574376825, https://github.com/getsentry/sentry-go/issues/103#issuecomment-574883037 and  https://github.com/getsentry/sentry-go/issues/103#issuecomment-574885317.
The new implementation changes the `Flush` behavior to wait until the
current in-flight requests are processed, inline with other SDKs and the
Unified API.
Fixes …
> fix: HTTPTransport.Flush panic and data race

- .golangci.yml
- helpers_test.go
Dropped `enable-all` and enabled all linters that are running right now explicitly.
fixes #142
> ci: enable linters explicitly

- README.md
GoDoc has the latest docs (master), go.dev has docs for all released
versions.
> Add badges to GoDoc and go.dev

- .craft.yml
The new statusProvider config option was added in craft@0.9.0 and
allows us to remove a dependency on zeus.ci for build status checks.
The includeNames option skips artifact fetching. Reference:
https://github.com/getsentry/craft/blob/59486ba128c3aa24e87e585a6a0b87667fc5b4c0/src/targets/base.ts#L67
> ci: Update craft config

- client.go
- hub.go
- sentry.go
- transport.go
> docs: Update Flush documentation

- transport.go
Removes a data race in HTTPTransport.
Fixes #141.
> fix: Synchronize access to disabledUntil

- client.go
- client_test.go
"err.Cause()" is nillable and leads to panic while using "err.Cause().Error()"
This pr adds handling for this nil case.
> handling "err.Cause() == nil" case

- .craft.yml
- CONTRIBUTING.md
- README.md
- Show how to prepare the changelog (at least how to get started)
- Remove bad flag to `craft`
- Update markdown block language to highlight contents as shell session
- Explicitly configure `craft` to check commit status using Travis
> Update release steps

- .travis.yml
- fasthttp/sentryfasthttp_test.go
- http/sentryhttp_test.go
Tests should allow us to make changes to `sentry-go` with some confidence that integrations still work.
Targeting `net/http` and `fasthttp` because other integrations (`echo`, `gin`, `iris`, `martini`, `negroni`) are similar to `net/http`, so we cover most of the surface area.
The tests cover 3 scenarios:
- Capturing panics
- Capturing message with request body
- Capturing message without request body
The tests in `sentryhttp` and `sentryfasthttp` are pretty similar, however need to account for differences in `net/http` and `fasthttp`.
Updates #97.
> Add tests for net/http and fasthttp integrations

- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- fasthttp/sentryfasthttp_test.go
- gin/sentrygin.go
- http/sentryhttp.go
- http/sentryhttp_test.go
- interfaces.go
- interfaces_test.go
- iris/sentryiris.go
- martini/sentrymartini.go
- negroni/sentrynegroni.go
- scope.go
- scope_concurrency_test.go
- scope_test.go
- transport_test.go
This change both limits the number of bytes that the SDK attempts to
read and buffer in memory, as well as delays as much work as possible.
It requires breaking changes to the exported API.
Notes on API changes:
```diff
- Request.FromHTTPRequest
+ NewRequest
```
The difference is that NewRequest does not read the request body.
FromHTTPRequest was called from HTTP middleware in integrations in the
beginning of the request handling flow. Attempting to read the whole
body there is often wasteful, since most requests should not result in
reporting an error to Sentry.
With this change, Scope.SetRequest keeps a lazy buffer that clones a
limited portion of the request body only if it is read by the user.
```diff
- Scope.SetRequest(Request)
+ Scope.SetRequest(*http.Request)
```
For most …
> feat: Limit reading bytes from request bodies

- .travis.yml
Go 1.14 has been released, so update the versions we test against.
Testing of Module mode outside of GOPATH can use the latest stable
release, thus not requiring a config update with each release of Go 1.x.
> ci: Test against Go 1.14, drop 1.11

- interfaces.go
Doc says that crashed thread should not have stacktrace, but instead, the `thread_id` attribute should be set on the exception https://docs.sentry.io/development/sdk-dev/event-payloads/exception/
> Add Exception.ThreadID field

- client.go
- client_test.go
Prior to this, calling `CaptureException`, `Recover` or `RecoverWithContext` with a `nil` error would send a message event to Sentry without a stack trace.
Looking at the Sentry issues list, and issue detail, all you see is "Called CaptureException with nil value" without a clue of what caused it.
This change turns that message into a `sentry.usageError` (new type) with a stack trace, making it easier to understand what is wrong and fix user code.
No stacktrace nor any clue where the incorrect call to `CaptureException` is.
Usage error with description and file name and line number information, plus source code context when available.
Without source context:
> fix: Report usage error including stack trace

- client.go
- interfaces.go
- marshal_test.go
- scope.go
- scope_concurrency_test.go
- scope_test.go
This gives us more flexibility to represent and manipulate time values,
as well as allow us to report values with sub-second resolution.
Fixes #190.
> fix: Use time.Time for timestamps

- client.go
- client_test.go
`scope.ApplyToEvent` may return nil, but is not checked in `prepareEvent`.
> fix: check for dropped event

- client.go
- transport.go
> Use http.RoundTripper in place of *http.Transport

- client.go
- client_test.go
Instead of reporting only the top parent of an error chain, report all errors that are part of the chain.
Supports chains of errors using the `Cause` method (used by popular error packages predating Go 1.13).
Support for errors using the `Unwrap` method (introduced in Go 1.13) or a combination of `Unwrap` and `Cause` will come briefly in a follow up.
Fixes #176.
---
**Example report of chained errors**
> Add support for chained errors

- client.go
- client_test.go
Unwrap was introduced in Go 1.13.
Fixes #137.
> feat: Support chained errors using Unwrap()

- go.mod
- integrations.go
- integrations_test.go
This changes getting modules from `runtime/debug` instead of getting it from `go.mod` or `vendor/modules.txt`.
Fixes #184
> Read module dependencies from debug.BuildInfo instead of go.mod

- client.go
In #185 the `event := NewEvent()` was changed to `event := &Event{Level: level}`. and caused this problem:`panic: assignment to entry in nil map` when you try to set value to `event.Extra`.
Extra useage example: https://github.com/getsentry/sentry-go/blob/master/example/with_extra/main.go#L56
> Fix event init in eventFromException

- README.md
This PR is a tweak change.
I fixed 404 link in Readme.
> Fix a missing link in README.md

- scope_test.go
If processedEvent is nil, it is a runtime panic to access any of its fields.
> fix: Stop test early on bad condition

- .travis.yml
- scope_test.go
While doing #144, realized it was behind a couple of versions so bumped.
> ci: Bump golangci-lint to v1.27.0

- interfaces.go
There is no need to embed the alias type in a struct when the aliased
type is already a struct itself and there are no new/shadowed fields.
A type conversion does the job of triggering the default json.Marshal
behavior.
> ref: Simplify MarshalJSON implementations

- transport.go
PR Addressing https://github.com/getsentry/sentry-go/pull/235#discussion_r434773906
We previously merged in new `Transaction` interfaces, and support for using the `envelopes` endpoint, but we only updated the async transport.
This PR updates `HTTPSyncTransport` to use `getRequestFromEvent`.
> feat: Add transactions to sync transport

- example/recover-repanic/main.go
This example demonstrates the use of SDK features (Hub, Scope and EventProcessor) to customize panic handling.
Related to #236.
> feat: Example of Recover followed by panic

- example/recover-repanic/main.go
This is a small change to the example for correctness.
The concurrency issue is subtle, but here is an attempt to explain it.
Keep in mind that:
- deferred calls happen in reverse order.
- to recover from panics in f, RecoverRepanic must defer a func call
before calling f.
If defer wg.Done() is part of f, the argument passed to RecoverRepanic,
it means it will be called before any deferred functions setup by
RecoverRepanic itself. If all goroutines started in the loop would call
wg.Done() before an event is reported to Sentry, the main goroutine
blocked on wg.Wait() would unblock and reach the end of func main,
terminating the execution of the program, consequently dropping any
other pending work in other goroutines, reporting to Sentry included.
---
I had this change locally and forgot …
> fix: wg.Done() must be outside RecoverRepanic

- CONTRIBUTING.md
- client.go
- dsn.go
- hub.go
- interfaces.go
- scope.go
- sentry.go
- stacktrace.go
Closes https://github.com/getsentry/sentry-go/issues/239
This PR adds comments to all Exported Types and Methods. It also links to the relevant SDK documentation where possible.
There are no code changes, only comments.
> doc: Add comments to all exported types and methods

- .golangci.yml
- client.go
- doc.go
- dsn.go
- dsn_test.go
- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- gin/sentrygin.go
- hub.go
- interfaces.go
- interfaces_test.go
- iris/sentryiris.go
- martini/sentrymartini.go
- negroni/sentrynegroni.go
- scope.go
- scope_test.go
- sentry.go
- sourcereader.go
- sourcereader_test.go
- stacktrace.go
- transport.go
One step towards better godoc output / better docs at godoc.org; not perfect.
No package overview:
Sometimes messy output on the console:
Basic package overview:
Better output on the console:
> Improve godoc output

- scope_concurrency_test.go
This fixes a go vet check enabled by default in Go 1.15 and run as part of go test.
Does not affect any SDK functionality.
---
See https://travis-ci.com/github/getsentry/sentry-go/jobs/350136321#L407
> fix: Dubious conversion from int to string in test

- .golangci.yml
- Add `whitespace` linter to check for unnecessary newlines at the start and end of functions, if, for, etc.
- Remove unnecessary exclude rules.
> Tweak golangci-lint config

- interfaces.go
- interfaces_test.go
- testdata/span.golden
- testdata/transaction_event.golden
`Data` is a valid field as part of the span interface, we should be including it.
https://develop.sentry.dev/sdk/event-payloads/span/
> feat(am): Add data field to Span interface

- client.go
- client_test.go
The original motivation was noticing that calling `rand.New` in `Client.processEvent` was odd.
Writing a small benchmark reviewed that calling `os.Hostname()` for every event was also wasteful.
This PR addresses only those two points and is not meant as a comprehensive optimization effort.
The two changes combined result in this [`benchstat`](//golang.org/x/perf/cmd/benchstat) output:
```
name             old time/op    new time/op    delta
ProcessEvent-16    10.3µs ±15%     0.8µs ± 3%  -92.11%  (p=0.000 n=8+7)
name             old alloc/op   new alloc/op   delta
ProcessEvent-16    6.45kB ± 1%    1.02kB ± 0%  -84.14%  (p=0.000 n=8+8)
name             old allocs/op  new allocs/op  delta
ProcessEvent-16      8.25 ± 9%      6.00 ± 0%  -27.27%  (p=0.000 n=8+8)
```
```
name            old …
```
> Avoid expensive operations in CaptureEvent hot path

- stacktrace.go
- stacktrace_external_test.go
Despite the name "filename", the field is supposed to contain "The path to the source file relative to the project root directory." [1]
Setting `Frame.Filename` to `filepath.Base(FrameAbsPath)` is a problem because it creates ambiguous paths and may affect the "Suspect Commits" feature.
Depending on how the binary is built, the Go runtime knows either the absolute path or the relative path of source files.
In the general case, it can be difficult to derive a correct "project-relative" path. Code built using Go Modules can be anywhere in the file system (not only under GOPATH). GOPATH can be multiple paths.
There was an attempt to trim paths in `raven-go` [2], but the approach there relies on GOROOT and GOPATH as configured for "future builds", and does not reflect how the running binary …
> fix: Set either Frame.Filename or Frame.AbsPath

- scope.go
- scope_test.go
I applied sentryecho middleware to my echo application, when capturing exception in `withScope`, the request body was not recorded.
Assign clone's request body to original scope
> fix: clone request body to new scope

- transport.go
- transport_test.go
Related: #212 (partial fix)
Closes: #214
> feat: Include original error when event cannot be encoded as JSON

- echo/sentryecho.go
Modified to support getting `sentry.Hub` instance from parent Context to include extra fields defined in the parent context.
Background -- we use sentry with echo web framework in a AWS lambda environment behind AWS API Gateway. We have top-level sentry instance defined with extra fields. 
The purpose of this change is to use the existing hub on context by default.
> Update echo middleware to get Hub instance from context

- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- gin/sentrygin.go
- http/sentryhttp.go
- iris/sentryiris.go
- martini/sentrymartini.go
- negroni/sentrynegroni.go
This allows users to setup a request-scoped Hub with relevant data in a middleware that runs before the web frameworks we integrate with.
A typical case is AWS Lambda + Web Framework. See https://github.com/getsentry/sentry-go/pull/217#issuecomment-635730182 for an example.
This is a follow-up on #217.
> feat: use Hub from request context when available

- http/sentryhttp.go
The Handler.HandleFunc is unnecessary as all uses can be replaced with Handler.Handle (an http.HandlerFunc implements http.Handler).
> fix(http): Deprecate HandleFunc, remove duplication

- integrations.go
- integrations_test.go
The previous behavior was to always set `"device"`, `"os"` and `"runtime"` contexts overwriting any pre-populated data.
This change allows users to set their own key-value pairs in those contexts, taking priority over the values set by the SDK.
Closes #186
Fixes #193
> feat: Make Environment Integration preserve existing context data

- client.go
Related to https://github.com/getsentry/sentry-go/issues/147.
Since the next release will be the first to include a doc comment for `AddGlobalEventProcessor`, let's mark it as deprecated as a first step and perhaps remove it in a future release.
> docs: Deprecate AddGlobalEventProcessor

- client.go
The [standard logger from Go's log package writes to stderr by default](https://github.com/golang/go/blob/0951939fd9e4a6bc83f23c42e8ddff02b29c997e/src/log/log.go#L76) and that is [the more conventional tradition](https://unix.stackexchange.com/a/331808).
This makes it so that enabling debug output without defining an output stream will use stderr instead of stdout. Users can then filter stderr to inspect SDK debug messages.
Fixes #154.
> feat: Send debug logging to stderr by default

- client.go
- client_test.go
> Recover and RecoverWithContext with arbitrary types

- client.go
- client_test.go
Calling `CaptureException` with a nil error reports a usage error to Sentry.
Before this change, `CaptureMessage("")` resulted in an event in Sentry called `'<unlabeled event>'`. `CaptureEvent(nil)` resulted in a run-time panic.
This change makes `CaptureMessage` and `CaptureEvent` behave similar to `CaptureException`, reporting an usage error to help users spot and fix instrumentation mistakes.
Fixes #202.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1330ee0]
goroutine 1 [running]:
github.com/getsentry/sentry-go.(*Client).prepareEvent(0xc00013a500, 0x0, 0x0, 0x147cc80, 0xc000156000, 0xc000014401)
client.go:399 +0x50
github.com/getsentry/sentry-go.(*Client).processEvent(0xc00013a500, 0x0, 0x0, …
```
> feat: Report bad usage of CaptureMessage and CaptureEvent

- .travis.yml
- go.mod
With the [release of go1.15](https://golang.org/doc/go1.15), update the list of supported versions.
> ci: Test against go1.15, drop go1.12 support

- interfaces.go
Neither Exception.RawStacktrace nor Thread.RawStacktrace are part of the protocol, they are internal fields used in Relay. Clients should not send that and it has no effect on data displayed in Sentry.
This is a breaking change to the published API, but one that fixes a bug -- those fields should not be used.
See:
https://github.com/getsentry/relay/blob/95d85eb662c0b7fa463de595cc6cdd0d8578ed5b/relay-general/src/protocol/exception.rs#L56-L57
https://github.com/getsentry/relay/blob/95d85eb662c0b7fa463de595cc6cdd0d8578ed5b/relay-general/src/protocol/thread.rs#L114-L115
> fix: Remove RawStacktrace

- client.go
Trying to write down what the current behavior is. This is going to be weird when `TracesSampleRate` will default to zero.
Alternatively, we could solve this with the functional options pattern overcoming the default value not matching the Go zero value for the type, but that would require a breaking API change right at `sentry.Init` 🤔
> doc: Clarify SampleRate documentation

- http/sentryhttp.go
The conversion is implied by the result type.
(As we go through it, rename the ResponseWriter parameter to the more
commonly used name 'w'.)
> ref: Remove unnecessary explicit type conversion

- example/http/main.go
- Check sentry.Init error
- Call sentry.Flush before server terminates
- Name ResponseWriter parameters 'w', as per common practice
- Remove WriteHeader line, as the net/http package does that for us
- http.ListenAndServe always returns a non-nil error, so we call
log.Fatal unconditionally
> ref: Update sentryhttp example

- example/http/main.go
- http/sentryhttp.go
Reverts the deprecation note added in
36c74322d86a295bf2cde8854576e42a77526bb3.
While sketching out tracing support for the sentryhttp package, I
realized that the deprecation was not necessary, since
sentryhttp.HandleFunc is particularly useful in one situation, and now
we have a more explicit example of that usage.
Typically, user code has either an http.Handler (http.HandlerFunc
implements http.Handler) or a function literal of type
func(http.ResponseWriter, *http.Request) to pass as argument.
Because sentryhttp.Handle already takes an http.Handler parameter, what
is left for sentryhttp.HandleFunc to be useful at is taking in a handler
function literal, implicitly converting it to an http.HandlerFunc so
that users don't have to write the explicit conversion, saving a bit of
noise.
> doc: Remove deprecation of sentryhttp.HandleFunc

- client.go
This is a simple fix that avoids allocating an event hint if one was provided to CaptureEvent
> fix: avoid unnecessary allocation in client.go

- hub.go
- hub_test.go
Equivalent change in JS:
https://togithub.com/getsentry/sentry-javascript/pull/2955
> fix: Hub.PopScope never empties the scope stack

- client.go
- dsn.go
While not extensive, the clarifications are meant to help people with
inline hints when they use the SDK in their favorite editor.
Changing a client's transport in unsupported because setting
Client.Transport does not configure the transport. While users could
theoretically call Transport.Configure themselves, the next problem is
that typically a single client is used by multiple hubs on concurrent
goroutines, and directly changing the transport without proper
syncronization is a data race.
> doc: Point users to preferable or more commonly used APIs

- .golangci.yml
- example/http/main.go
- http/example_test.go
- http/sentryhttp.go
The major point is to promote instrumenting higher up in the HTTP
handler hierarchy, such that Sentry instrumentation takes only one line,
instead of wrapping many individual handlers.
- Add go doc example with minimal steps for instrumenting web servers.
- Overhaul doc comments.
- Replace executable example with something a little bit more realistic,
which we can build upon to show tracing instrumentation later.
> doc: Revamp sentryhttp documentation

- .travis.yml
This makes the Travis builds on the legacy GOPATH mode succeed.
They were failing because Iris imports `github.com/russross/blackfriday/v2` which cannot be installed in GOPATH mode.
> ci: Update install steps to make GO111MODULE=off work

- util.go
This is to make use of a (future) protection against rogue code that
changes the value of rand.Reader.
The distinction may only be relevant in Go 1.17 onwards, while Go 1.16
is not released yet. The change has a chance of being backported to
1.16.x, though.
> ref: Use crypto/rand.Read, not crypto/rand.Reader

- client.go
- internal/debug/transport.go
Not a supported feature, but useful nonetheless.
Similar to GODEBUG, SENTRYGODEBUG is a comma-separated list of key=value
pairs, though the only recognizable pair right now is dumphttp=1 to dump
HTTP requests and responses to stderr.
> feat: Add helper to debug outgoing HTTP requests

- interfaces.go
- interfaces_test.go
- marshal_test.go
- testdata/span.golden
- testdata/transaction_event.golden
- tracing.go
- tracing_test.go
This overhauls the tracing-related types and their serialization to
JSON.
We rename Event.StartTimestamp, Span.StartTimestamp and
Span.EndTimestamp to remove the "stamp" suffix in preparation to use
StartTime and EndTime for spans when full tracing support is added.
Preferring the shorter name because it is shorter and equally clear, and
the type is time.Time.
This is a breaking change, but should not affect most users, as those
names were only used by the Sentry OpenTelemetry Exporter (we can update
it) and are marked as experimental APIs.
> feat: Add types and rename fields for tracing

- README.md
- client.go
- doc.go
- example/http/main.go
- http/sentryhttp.go
- http/sentryhttp_test.go
- hub.go
- internal/crypto/randutil/randutil.go
- internal/crypto/randutil/randutil_test.go
- scope.go
- span_recorder.go
- traces_sampler.go
- traces_sampler_test.go
- tracing.go
- tracing_test.go
- transport.go
- util.go
This adds the StartSpan function and related APIs to the SDK.
The initial support focuses on manual instrumentation and HTTP servers
based on net/http.
Tracing is opt-in. Use one of the new options, TracesSampleRate or
TracesSampler, when initializing the SDK to enable sending transactions
and spans to Sentry.
The tracing APIs rely heavily on the standard Context type from Go, and
integrate with the SDKs notion of scopes.
See example/http/main.go for an example of how the new APIs are meant to
be used in practice.
While the basic functionality should be in place, more features are
planned for later.
> feat: Initial tracing implementation

- .github/workflows/ci.yml
This runs most of what Travis executes inside of Github actions.
Running against the latest golang has not been ported. All other modes have been ported.
I will enquire as to how to get the latest golang running with the setup-go action.
Since I do not have write access on the upstream repo the checks won't show up on this PR.
You can view the results on my [fork](https://github.com/armenzg/sentry-go/actions/runs/481210918).
Related to https://github.com/getsentry/sentry-go/issues/313.
> Run Travis & GH actions CI side by side

- .github/workflows/ci.yml
> Go tip version

- transport.go
- transport_test.go
This fixes the two transport implementations to drain (up to a safe limit) and close the response body from API calls, allowing the net/http client to reuse connections.
Fixes #316.
Closes #317 (replaces it).
Thanks @laoleesch.
> fix: drain and close API response bodies

- client.go
- internal/debug/transport.go
Add a new SENTRYGODEBUG option httptrace to print DSN resolution and TCP
connection information, including whether connections are being reused.
Rename internal debug option dumphttp -> httpdump for symmetry with
httptrace (that derives from the net/http/httptrace package name).
The new option was used to reproduce / debug #316.
> feat: debug connection reuse

- interfaces.go
It took a few weeks and eventually an email to support to figure out that the `Type` field was used as the main title in the Sentry UI. I figured I would save others the same confusion by adding some comments.
> exception: add comment describing field usage

- scope.go
- tracing_test.go
Otherwise the trace context of child spans or other unrelated value in
the scope ends up breaking the transaction representation.
Fixes #318
> fix: Do not override trace context of transactions

- tracing.go
- tracing_test.go
Pending spec clarification since implementation in Relay and different
SDKs diverged.
For now sending data in Event.Extra gets the information into the
Transaction view in Sentry.
Fixes #311.
> fix: Send root span data as Event.Extra

- client.go
- tracing_test.go
Transactions should be sampled only by `TracesSampleRate` or `TracesSampler`, and the general `SampleRate` does not apply.
See https://develop.sentry.dev/sdk/performance/#sampling
> fix: Do not double sample transactions

- go.mod
- go.sum
The older version has more dependencies than the latest version does.
> go.mod: update go-cmp to v0.5.5

- transport.go
Shedding some light on how the two transports differ and when you'd want to use one over the other.
> docs(transports): More details on Transport implementations

- fasthttp/sentryfasthttp_test.go
The current master branch from fasthttp has unreleased changes that break our tests (when running against master in GOPATH mode).
We thus make the tests less dependent on uninteresting (from sentry-go's perspective) behavior.
> test(fasthttp): Ignore some HTTP headers

- scope.go
- scope_test.go
Closes #348.
- We don't need to allocate a new slice when cloning because `Scope.eventProcessors` is append-only; `Scope.AddEventProcessor` always creates a new slice, so we can share the backing array.
- Include a couple of tests.
> fix(scope): Include event processors in clone

- transport.go
- transport_test.go
Internal change.
We only need to look at HTTP headers, not the full response value.
> ref(transports): Simplify retryAfter arguments

- .github/workflows/test.yml
This helps us prevent accidentally having an inconsistent go.mod file
after changes to dependencies.
> ci: Require go.mod to be tidy

- example/recover-repanic/main.go
- example/with_extra/main.go
When the examples and accompanying documentation were written, 'all events' meant 'error events'. 
With transactions added to the SDK, `BeforeSend` is only applied to error events while all `EventProcessor` functions (on client, scope or global) are applied to all outgoing events (errors and transactions).
> docs: Fix mentions to 'all events'

- client.go
- example/with_extra/main.go
And apply [suggestion from a previous change](https://github.com/getsentry/sentry-go/pull/350#discussion_r635423967).
Closes #341.
> docs: Clarify that BeforeSend is not called for transactions

- .github/workflows/test.yml
We run tests on well-supported platforms, such that there is little
chance the race detector will detect a race in one operating system but
not in the others.
We can save resources, human and machine, by not using the race detector
too many times in every PR.
To be on the safe side, leave it on for pushes to master and release
branches.
Remove it from GOPATH Mode completely since it is redundant.
> ci: Use race detector only once for PRs

- .golangci.yml
- transport_test.go
It has not given us much value. Instead of adding 'nolint' lines for the
few cases where we do need long lines, better not have this linter and
keep the code base free of linter pragmas.
> ci: Disable lll linter

- go.mod
This is complimentary to [dropping support for Go 1.13](https://github.com/getsentry/sentry-go/pull/346).
We can now declare the minimum Go version to be 1.14.
We still support the last three stable Go releases, which is more than
what the Go project and community normally do (the norm is to support
the last two stable releases).
https://golang.org/doc/modules/gomod-ref
> build: Bump go.mod Go version to 1.14

- .golangci.yml
- internal/ratelimit/category.go
- internal/ratelimit/category_test.go
- internal/ratelimit/deadline.go
- internal/ratelimit/doc.go
- internal/ratelimit/map.go
- internal/ratelimit/map_test.go
- internal/ratelimit/rate_limits.go
- internal/ratelimit/rate_limits_test.go
- internal/ratelimit/retry_after.go
- internal/ratelimit/retry_after_test.go
- transport.go
- transport_test.go
This adds support for parsing the `X-Sentry-Rate-Limits` and rate limiting errors and transactions independently.
> feat(transports): Category-based Rate Limiting

- sentry.go
- transport.go
- transport_test.go
The default User-Agent for outgoing requests using Go's HTTP client is `Go-http-client/1.1`.
Instead of reporting this generic string that confuses with any other Go program, identify the SDK and version used to send out requests.
The intent here is to facilitate debugging.
> feat(transports): Report User-Agent identifying SDK

- client.go
- client_test.go
- fasthttp/sentryfasthttp_test.go
- http/sentryhttp_test.go
- tracing_test.go
- util.go
Attempts to guess the release info, either by getting the last git
commit hash or by looking up some know environment variables that tracks
release identification.
Had to make changes on some tests, though I am not sure if what I wrote there is appropriated.
Closes #335.
> feat: Automatic Release detection (#335)

- client.go
- example/basic/main.go
- util.go
- Briefly explain importance of setting a release
- Document that release may be derived from env or git
- Recommend setting the release during build
- Apply build-time release pattern to examples
This is a follow up on https://github.com/getsentry/sentry-go/pull/363.
> More ClientOptions.Release documentation

- hub.go
- hub_test.go
LastEventID was meant to be used for error IDs, and with the addition of the transaction event type, those use cases got affected.
See https://github.com/getsentry/develop/issues/431.
> Do not change Hub.lastEventID for transactions

- example/http/main.go
For https://github.com/github/codeql-go/issues/650.
CodeQL is still not able to understand `"%q"` right now, but still we can make the change for better/safer example code.
> Sanitize user input before logging in example code

- .github/workflows/test.yml
- go.mod
Continuing with our cadence to support the last 3 Go releases.
See [our README](https://github.com/getsentry/sentry-go/blob/6f773c6ed0047c04787e986536a4478be1452162/README.md#requirements).
> build: Bump supported Go versions

- .github/workflows/test.yml
- go.mod
- go.sum
Commit generated with this command
```
go mod tidy -go=1.17 -compat=1.15
```
Using Go version 1.17.5.
The idea is to enable consumers of sentry-go to be able to use module
graph pruning (Go 1.17+ required), such that dependencies of sentry-go
that are otherwise unused by end users can be pruned away.
See https://github.com/getsentry/sentry-go/issues/156#issuecomment-1027175141
Also update CI workflow to check for go.mod tidiness using the same line
as used to generate this commit. Update data race tests that were still
accidentally being run on Go 1.16 instead of 1.17.
> build: Bump Go version in go.mod

- stacktrace.go
Some error types may return stack traces already defined as `[]runtime.Frame`.
In this case, the program counter will be in the `PC` field.
fixes: #391
> fix: When extracting PCs from stack frames, try the `PC` field

- .github/workflows/codeql-analysis.yml
It now requires `permissions: security-events: write` for it to work.
> ci: Update GraphQL config with appropriate permissions

- .golangci.yml
- client.go
- example/iris/main.go
- example/recover-repanic/main.go
- iris/sentryiris.go
- scope.go
- stacktrace.go
- transport.go
- `maligned` is now included in `govet`
- `golint` is dropped in favor of `revive`
- `scopelint` is dropped in favor of `exportloopref`
- `interfacer` is deprecated
- `//go:build go1.13` is new syntax in `1.17` - https://go.dev/doc/go1.17#go-command
- changing min. TLS to `1.2` as its `gosec` requirement
- the rest is stylistic
> misc: Update deprecated linters and fix code for remaining rules

- .github/workflows/lint.yml
To follow all current defaults.
> ci: Bump golangci-lint version in GH workflow

- dsn.go
- dsn_test.go
- transport.go
Closes https://github.com/getsentry/sentry-go/issues/416
> ref: Change DSN ProjectID to be a string

- .github/workflows/lint.yml
Required for PRs to be linted properly, eg. https://github.com/getsentry/sentry-go/runs/6095100285?check_suite_focus=true
ref https://github.com/golangci/golangci-lint/issues/2649
> ci: Update golangci-lint-action to 1.45.2 for Go 1.18 support

- .github/workflows/lint.yml
- .github/workflows/test.yml
There are some changes required to support go1.18, and I want the CI to stay green until we make them.
> ci: Use go1.17 for lint/test until we officially support go1.18

- .gitignore
- client.go
> add: max-depth options

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- fasthttp/sentryfasthttp_test.go
- go.mod
- http/sentryhttp_test.go
- internal/ratelimit/category.go
- tracing_test.go
Swapped `strings.Title` for `cases.Caser`, as former is deprecated.
Other than that, minor CI/test updates, and no functional changes.
NOTE: This version drops support for Go 1.15, however no changes have been made that would make the SDK not work with Go 1.15. The currently supported Go versions are the last 3 stable releases: 1.16, 1.17 and 1.18.
> ci: Test against go1.18, drop go1.15 support

- tracing.go
- tracing_test.go
**tl;dr: This allows users to easily add traces from sources other than http.Request**
Recently ran in to a situation where we want to add tracing between services where not all of them uses HTTP to communicate (in this case, rabbitMQ) so I refactored a bit and added a new exposed function that continues from a trace header.
This does not introduce any breaking changes from what I can see and the tests does of course still pass.
> feat: :sparkles: Added function to continue from trace string

- client.go
- scope.go
- stacktrace.go
- transport.go
```bash
go test ./... -run=$^ -bench=Benchmark -benchmem -count=10 > old.txt
go test ./... -run=$^ -bench=Benchmark -benchmem -count=10 > new.txt
benchstat old.txt new.txt
```
```text
name              old time/op    new time/op    delta
ProcessEvent-12     1.50µs ±14%    1.56µs ±22%     ~     (p=0.684 n=10+10)
NewStacktrace-12    8.24µs ±25%    4.34µs ±14%  -47.30%  (p=0.000 n=10+10)
name              old alloc/op   new alloc/op   delta
ProcessEvent-12       946B ± 0%      939B ± 0%   -0.73%  (p=0.000 n=10+7)
NewStacktrace-12    7.36kB ± 0%    2.30kB ± 0%  -68.70%  (p=0.000 n=10+10)
name              old allocs/op  new allocs/op  delta
ProcessEvent-12       4.00 ± 0%      4.00 ± 0%     ~     (all equal)
NewStacktrace-12      15.0 ± 0%       4.0 ± 0%  -73.33%  (p=0.000 n=10+10)
```
> Optimize stacktrace from 7.36kB to 2.30kB and speed too

- CHANGELOG.md
- interfaces.go
- interfaces_test.go
- scope.go
- scope_test.go
> feat: Extend User struct by adding Data, Name and Segment

- doc.go
- dsn_test.go
- stacktrace_external_test.go
- stacktrace_test.go
- tracing.go
- util.go
> docs: Run go fmt

- CHANGELOG.md
- client.go
- fasthttp/sentryfasthttp_test.go
- http/sentryhttp_test.go
- interfaces.go
- interfaces_test.go
As `scope.SetUser` has to be explicitly called by the user, I did not add a check for `SendDefaultPii` there. 
Closes #175
> feat: Add ClientOptions.SendDefaultPii

- CHANGELOG.md
- client.go
- fasthttp/sentryfasthttp_test.go
- http/sentryhttp_test.go
- interfaces.go
- interfaces_test.go
re: https://github.com/getsentry/sentry-go/pull/485#discussion_r1011500255
> ref: Rename ClientOptions.SendDefaultPii to ClientOptions.SendDefaultPII

- example/logrus/main.go
- go.mod
- logrus/logrusentry.go
- logrus/logrusentry_test.go
This PR adapts my free-standing logrus hook (https://gitlab.com/flimzy/logrusentry) for inclusion in this repo. Closes #43 
There's a good chance this hook doesn't take advantage of all available/relevant Sentry features.  But it's been serving me well for several years now, at at least three different companies.  Please advise if there are any functional or stylistic changes that are desired. I'm happy to do what I can to get this included in this repo.
> Add logrus support

- dynamic_sampling_context.go
- dynamic_sampling_context_test.go
- http/sentryhttp.go
- interfaces.go
- tracing.go
This adds support in case we're the head SDK that starts the trace for Dynamic Sampling.
- Add `DynamicSamplingContextFromTransaction`
- Add `Span.Source`
- Set the correct sample rate on the Span
Populating the envelop header will be done in #491 
Closes #457
> [Dynamic Sampling] Head of trace

- tracing.go
Cloning the Hub inside `StartTransaction` is not necessary and can mess up the scope.
Calling `sentry.Init()` already creates the "initial" hub, integrations have to make sure to attach it to the context.
Closes #502
> fix: Do not clone the hub inside StartTransaction

- tracing.go
Added the case where a legacy FE/mobile SDK would send a `sentry-trace` header but no `baggage` header.
> Create an empty DSC in case there is no baggage header

- README.md
Based on the feedback we got in #514, I changed the link to point to the GitHub release instead, as they provide a more useful changelog.
> docs: Update link to releases in README.md 

- client_test.go
- example/feature-showcase/main.go
- example/flush/main.go
- example/multiclient/main.go
- example/recover/main.go
- example/synctransport/main.go
- example/with_extra/main.go
- hub_test.go
To be on the safe side, let's not use domains in tests and examples that might be in actual use.
`example.com` should be a safe choice for those purposes: https://en.wikipedia.org/wiki/Example.com
> fix: Use "example.com" host in example/test DSNs

- dynamic_sampling_context.go
- dynamic_sampling_context_test.go
- tracing.go
- tracing_test.go
From https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/#freezing-dynamic-sampling-context:
> When an SDK receives an HTTP request that was "instrumented" or "traced" by a Sentry SDK, the receiving SDK should consider the incoming DSC as instantly frozen. Any values on the DSC should be propagated "as is" - this includes values like "environment" or "release".
> SDKs should recognize incoming requests as "instrumented" or "traced" when at least one of the following applies:
> The incoming request has a sentry-trace header
The incoming request has a baggage header **containing one or more keys starting with "sentry-"**
Therefore, when creating a DSC from a header, let's freeze it only when there's at least one `sentry-` value.
> fix(dynamic-sampling): Do not freeze DSC if no Sentry values are present

- CHANGELOG.md
- tracing.go
- tracing_test.go
This is helpful to have for the ongoing OTel work (happening in #537).
> ref(tracing): Add constants for "sentry-trace" and "baggage" header names

- CHANGELOG.md
- dsn.go
- dsn_test.go
Unsure about `func (dsn Dsn) GetScheme() string` instead of `func (dsn Dsn) GetScheme() sheme`.
I want to avoid exporting `type scheme string` though 🤔 
This is needed for OTel (https://github.com/getsentry/sentry-go/pull/537).
> feat: Add DSN getters

- CHANGELOG.md
- tracing.go
- tracing_test.go
This PR adds `Span.SetDynamicSamplingContext` method that allows to set the given dynamic sampling context on a transaction. For spans it does nothings.
This is needed for the OTel work (#537).
> feat(tracing): Add Span.SetDynamicSamplingContext method

- CHANGELOG.md
- tracing.go
- tracing_test.go
This is needed for OTel (https://github.com/getsentry/sentry-go/pull/537).
> feat: Add Span.SetData()

- CHANGELOG.md
- tracing.go
- tracing_test.go
This is needed for OTel (https://github.com/getsentry/sentry-go/pull/537).
> feat: Add Span.IsTransaction()

- .github/workflows/test.yml
- .gitignore
- Makefile
At the moment we only run test/coverage commands for the root module. 
Given the ongoing OTEL work (#537), we want to run the CI steps also for the new submodule(s).
The general approach for `test`/`test-coverage` targets was taken from https://github.com/open-telemetry/opentelemetry-go/blob/main/Makefile, and we can further iterate, if necessary.
> test: Run tests and collect coverage for all submodules, if present

- CHANGELOG.md
- tracing.go
- tracing_test.go
A new SpanOption needed for the OTel work (#537).
Can be used to control the sampling flag when creating a new transaction.
> feat(tracing): Add a new SpanOption: SpanSampled

- CHANGELOG.md
- tracing.go
- tracing_test.go
Part of the OTel work (#537).
In this PR:
1. Add TraceParentContext structure: it represents a parsed `sentry-trace` header.
* Add a helper function: `ParseTraceParentContext`
2. Update `updateFromSentryTrace` to return a boolean status (whether the span has been updated).
> feat(tracing): Add TraceParentContext and helper functions

- helpers_test.go
- otel/helpers_test.go
- otel/propagator.go
- otel/propagator_test.go
- tracing.go
- tracing_test.go
Thanks to #558, we can now fix the DSC/baggage propagation for non-transaction spans in the OTel propagator.
Fixes #553.
> fix(otel): Fix Dynamic Sampling context propagation for nested spans

- helpers_test.go
- internal/testutils/asserts.go
- otel/helpers_test.go
- otel/span_processor_test.go
Here we move all assert* helper functions from the root and "otel" modules to a new `internal/testutils` package.
Also: add AssertTrue and AssertFalse helpers.
> ref(test): Move assert* helpers to internal package

- .craft.yml
Craft v0.35.0 [supports](https://github.com/getsentry/craft/blob/master/CHANGELOG.md#0350) `tagOnly` attribute for github target, so we can already prepare for the next release, where the new submodule (`otel`) becomes the part of the repo.
For now we agreed to have version parity between the root SDK and all submodules, for simplicity.
> release: Update .craft.yml to be ready for otel submodule release

- dynamic_sampling_context_test.go
- otel/propagator.go
- otel/span_processor_test.go
- tracing.go
- tracing_test.go
This fixes an issue, where someone would call `span.ToBaggage` to fetch the `DynamicSamplingContext` to attach it to an outgoing HTTP request "baggage" header or to render it in an HTML template as a "baggage" meta tag before the transaction is finished.
We need to freeze the DynamicSamplingContext in such cases, as any mutations after the DynamicSamplingContext was propagated to a downstream SDK mess up DynamicSampling.
> fix: Create a frozen DSC when calling ToBaggage

- otel/go.mod
- otel/go.sum
Looking at the [opentelemetry-go changelog](https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md), in 1.11.0 a potential vulnerability was fixed: https://pkg.go.dev/vuln/GO-2022-0493
So let's not go lower than 1.11.0.
> fix(otel): Reduce minimal required OTel SDK version to 1.11.0

- go.mod
- internal/otel/baggage/README.md
- internal/otel/baggage/baggage.go
- internal/otel/baggage/baggage_test.go
These changes to `baggage.go` fix a few issues that are happening now in violation of [the baggage spec](https://www.w3.org/TR/baggage/) (or at least my understanding of it):
1. Baggage string value `one%20two` should be properly parsed as "one two"
2. Baggage string value `one+two` should be parsed as "one+two"
3. Go string value "one two" should be encoded as `one%20two` (percent encoding), and NOT as `one+two` (URL query encoding).
4. Go string value "1=1" might be encoded as `1=1` ([the spec says:](https://www.w3.org/TR/baggage/#value) "Note, value MAY contain any number of the equal sign (=) characters. Parsers MUST NOT assume that the equal sign is only used to separate key and value."). `1%3D1` is also valid, but to simplify the implementation we're not doing it.
* [The original …
> fix(baggage): Update baggage parsing and encoding in vendored otel package

- otel/context.go
- otel/helpers_test.go
- otel/propagator.go
- otel/propagator_test.go
After #568, we can finally fix the issue in the propagator that resulted in dropping baggage.
Now we only use our vendored baggage implementation with the fixes that hopefully make our implementation consistent with baggage implementations in other Sentry SDKs.
> fix(otel): Use vendored bagggage implementation in propagator

- scripts/bump-version.sh
We need this so that after releases submodules depend on the correct version of the root module.
> fix(release): Bump root module version in submodules

- .github/workflows/test.yml
- Makefile
In the new module/submodule world, it's not enough to do e.g. `go build ./...`, since it'll ignore submodules.
> fix(ci): Run "build", "vet", and "mod tidy" for all submodules

- interfaces.go
- interfaces_test.go
This adds support for the exception `mechanism` field, based on the [`relay` schema of the field](https://github.com/getsentry/relay/blob/e785f9a22adef018cec8785a7dec289a6ae74165/relay-general/src/protocol/mechanism.rs#L94-L159).
Primarily, I'd like to be able to annotate exceptions with this data to make the UI more useful. For instance, we have a gRPC interceptor that recovers from `panic`, and I think it would be useful to set the `handled` bit to `false` so that we get the additional UI embellishment (the red skull and "Unhandled" flag) when endpoints panic (versus returning an explicit status or error). This would likely be useful to other HTTP integrations as well.
> feat: add support for exception mechanism metadata

- LICENSE
Follow-up to #583.
Part of https://github.com/getsentry/team-ospo/issues/56.
> Correct copyright holder name

- README.md
Sigh. Also this!
Follow-up to #584 and #583.
Part of https://github.com/getsentry/team-ospo/issues/56.
> Update license in README

- otel/event_processor.go
- otel/event_processor_test.go
- transport.go
This patches the following issue: when [creating a transaction in the span processor](https://github.com/getsentry/sentry-go/blob/f03b31a4a314fda36229c131a20306ffd686f2e9/otel/span_processor.go#L50-L56), we later overwrite its SpanID/TraceID. The problem is, the trace context is also set on the scope when the span is started: https://github.com/getsentry/sentry-go/blob/f03b31a4a314fda36229c131a20306ffd686f2e9/tracing.go#L176
So ultimately we need to either/or:
1. Pass additional SpanOptions to StartTransaction that set the right SpanID/TraceID right away
2. Overwrite the trace context later.
Here I'm taking approach 2 because it's easier, but generally speaking I believe we should review setting trace context (and a few other tracing related things) on the scope.
> fix(otel): Overwrite "trace" context in Sentry error

- CHANGELOG.md
Forgot to mention `text` version bump in the CHANGELOG.
> doc: Mention golang.org/x/text version bump in CHANGELOG

- otel/span_processor.go
- tracing.go
- tracing_test.go
ref https://github.com/getsentry/sentry-go/issues/596
This PR adds the `SetContext` struct method to the span struct.
This allows us to remove the usage of setting context on the scope in the OpenTelemetry span processor
> feat(tracing): Introduce span.SetContext

- otel/internal/utils/spanattributes.go
- otel/span_processor.go
- otel/span_processor_test.go
This fixes a few cases when span description for HTTP spans was super basic (e.g. for HTTP client spans). 
So what looked like this:
https://sentry-sdks.sentry.io/performance/otel-demo-checkoutservice:64da25426e624ac89e9dc0789207100d/?environment=production-dev&project=4504524774047744&query=&referrer=performance-transaction-summary&statsPeriod=1h&transaction=hipstershop.CheckoutService%2FPlaceOrder&unselectedSeries=p100%28%29
...is now this:
https://sentry-sdks.sentry.io/performance/otel-demo-checkoutservice:366ed120baf0449c8b9af96b89482692/?environment=staging-dev&project=4504524774047744&query=&statsPeriod=1h&transaction=hipstershop.CheckoutService%2FPlaceOrder#span-6e440558257cee22
Fixes #557, part of https://github.com/getsentry/team-webplatform-meta/issues/32
> fix(otel): Better handling for HTTP span attributes

- .github/workflows/test.yml
Looks like the GOPATH tests are failing because opentelemetry-go now has 1.19+ symbols (`atomic.Bool`, `atomic.Pointer`) in their main branch.
Example: https://github.com/getsentry/sentry-go/actions/runs/4563862504/jobs/8052889793
We might want to consider dropping the GOPATH builds/support altogether. Opened https://github.com/getsentry/sentry-go/issues/616 to discuss that.
> fix(build): Temporarily remove otel module when building in GOPATH mode

- internal/otel/baggage/baggage.go
- internal/otel/baggage/baggage_test.go
- internal/otel/baggage/internal/baggage/baggage.go
"internal/otel/baggage" package was initially vendored from opentelemetry-go, and then later we made some updates to it. According to our new attribution policy, adding some links to the original files (copyright notes are already there).
Ref https://github.com/getsentry/team-webplatform-meta/issues/42, https://github.com/getsentry/team-ospo/issues/120
AFAIK this is the only place where we need to attribute 3rd party code.
> doc: Update attributions for vendored "baggage"

- .github/workflows/lint.yml
Sometimes we're getting timeouts because the linting step cannot finish within 1 minute, so let's try to raise the timeout.
Example of the timeout: https://github.com/getsentry/sentry-go/actions/runs/4563862500/jobs/8052889794
Most of the time the step takes just a few seconds, but sometimes it doesn't 🤷  Taking the easiest way out for now.
> fix(ci): Increase timeout for golangci-lint

- doc.go
At https://pkg.go.dev/github.com/getsentry/sentry-go they already show the README.md from the repository, and what we've had in `doc.go` (displayed under "Documentation") has been partially outdated. 
To avoid these drifts in the future, let's just link to the repository and official docs in `doc.go`.
> doc: Link to the repository and official docs in doc.go

- http/sentryhttp.go
- otel/propagator_test.go
- otel/span_processor.go
- tracing.go
- tracing_test.go
As a follow-up to #611, let's unify the (applicable) span options by prefixing them with "With":
SpanSampled -> WithSpanSampled
OpName -> WithOpName
TransactionName -> WithTransactionName
The original names are deprecated: not removed right away, but there's a task to do it in a version or two: https://github.com/getsentry/sentry-go/issues/625
Not touching `ContinueFromRequest`, `ContinueFromHeaders`, and `ContinueFromTrace` since they have slightly different semantics.
**Why?**
1. Without the prefix some newly introduced span option names collide with existing types names and/or Span fields.
2. This is a common pattern e.g. in OpenTelemetry: https://github.com/open-telemetry/opentelemetry-go/blob/1b55281859bfaf4b03b7968a059c5239cf8c7a20/trace/config.go#L278-L333
**Note:** some docs will …
> ref: Add span options aliases (WithSpanSampled, WithOpName, WithTransactionName)

- client.go
- interfaces.go
> feat: Add Event.SetException

- otel/internal/utils/sentryrequest.go
- otel/span_processor_test.go
If we can't fetch a hub from the `ctx`, we now fallback to the global hub.
I also added the project id to not solely rely on the hostname.
> fix: Improve isSentryRequestUrl

- dsn.go
- dsn_test.go
- interfaces.go
- logrus/logrusentry_test.go
- transport.go
- transport_test.go
To move forward on initiatives like https://github.com/getsentry/team-replay/issues/70 and https://github.com/getsentry/team-webplatform-meta/issues/45, we decided to remove the `/store` endpoint from the Go SDK.
These changes require a self-hosted version of Sentry 20.6.0 or higher. If you are using a version of [self-hosted Sentry](https://develop.sentry.dev/self-hosted/) (aka onpremise) older than 20.6.0 then you will need to [upgrade](https://develop.sentry.dev/self-hosted/releases/).
I removed quite a few things from `logrusentry_test.go`.
My reasoning is that we mostly care about testing `entryToEvent`, as all other functionality is wrapped into `CaptureEvent`. Making the tests work again would require copying a lot of functionality from `client_test.go`, something I'm not keen on …
> feat: Remove store endpoint

- otel/internal/utils/sentryrequest.go
- otel/span_processor_test.go
This is a follow-up on #632, to add better error handling as well as a better comparison of the span attribute URL.
Has to be merged after #631.
> ref: Improve isSentryRequestUrl

- CHANGELOG.md
Before the release: 
Let's release it on Monday.
> doc: Prepare 0.21.0 release

- tracing.go
- tracing_test.go
Transaction source should be one of the predefined values as described by the envelopes protocol: https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations
The safest way to do for Go seems to be checking the source in `Span.toEvent()`: we don't currently have setters for `Span.Name` and `Span.Source`, so adjusting the source earlier may be not enough.
Fixes https://github.com/getsentry/sentry-go/issues/588
Related to https://github.com/getsentry/sentry-go/issues/511
> fix(tracing): Make sure a valid source is set on a transaction event

- CHANGELOG.md
- stacktrace.go
- stacktrace_test.go
The stack trace in-app field had `omitempty` so it wouldn't be sent in JSON when it was false. This wasn't correct as that would actually lead to exactly the opposite behaviour in sentry.io where the frame would show as `in-app=true` (the default when the field is not present on the frame).
> fix: stack-trace `in_app` false being omitted

- gin/sentrygin.go
- gin/sentrygin_test.go
- tracing.go
add missing transactions for gin
> feat(gin): Add transactions to Gin integration

- client.go
- dynamic_sampling_context.go
- hub.go
- integrations.go
- interfaces.go
- span_recorder.go
Removes use of `client.Options()` from the internal code to avoid copying the options object.
> refactor: use client.options internally to avoid copying

- _examples/basic/main.go
- _examples/recover-repanic/main.go
- scope.go
- scope_test.go
- tracing.go
- tracing_test.go
Fixes https://github.com/getsentry/sentry-go/issues/570
Here we introduce `cloneContext` that should be used in multiple places to avoid issues like in https://github.com/getsentry/sentry-go/issues/570. 
Note: `cloneContext` does not do a deep copy of `Context` values (which are of type `interface{}`), so there are cases where it's still possible to catch panics if you do weird things with `Context` values. But this, I believe, is out of scope of the SDK responsibility.
> fix: Clone scope.Context in multiple places to avoid concurrent reads/writes

- profiler_test.go
Enables the TestProfilerCollection/RealTicker test in CI but with a long duration, in hopes it won't be flaky in CI.
Requested in https://github.com/getsentry/sentry-go/pull/626/files/c3ce952783a3b8d68042fd8367add1dad837e5b9#r1213167528
> test: real ticker profiling in CI with a long duration

- CHANGELOG.md
> doc: Prepare 0.22.0 release

- transport_test.go
This test got increasingly flake lately, specifically on Windows. Let's see if it makes things better.
> fix: Increase flush timeout in TestHTTPTransport

- tracing.go
- tracing_test.go
Span.Finish() should only be executed once, all the further executions should be no-ops. This should also prevent potential data races when Finish() is (erroneously) called concurrently.
Closes https://github.com/getsentry/sentry-go/issues/587
> fix(tracing): Make Span.Finish a no-op when the span is already finished

- dynamic_sampling_context.go
- dynamic_sampling_context_test.go
- otel/propagator_test.go
- otel/span_processor_test.go
- tracing_test.go
> feat(tracing): Add the sampling decision to the trace envelope header

- check_in.go
- client.go
- client_test.go
- hub.go
- hub_test.go
- interfaces.go
- marshal_test.go
- sentry.go
- testdata/json/checkin/000.json
- testdata/json/checkin/001.json
- testdata/json/checkin/002.json
Closes #659 
This implementations looks up to:
- https://github.com/getsentry/sentry-php/pull/1467
- https://github.com/getsentry/sentry-php/pull/1511
- https://github.com/getsentry/sentry-javascript/commit/a2cda4df089ad372f721c94b07dd752211acf820
- https://github.com/getsentry/sentry-javascript/pull/8039
> feat(crons): initial cron support

- client_test.go
- fasthttp/sentryfasthttp_test.go
- gin/sentrygin_test.go
- http/sentryhttp_test.go
- interfaces.go
- logrus/logrusentry_test.go
- scope.go
- scope_concurrency_test.go
- scope_test.go
- tracing_test.go
- transport.go
- transport_test.go
This is similar to how [`sentry-rust` supports attachments](https://docs.rs/sentry/0.31.5/sentry/struct.Scope.html#method.add_attachment).
Resolves #574.
> feat: Attachments support

- tracing.go
- tracing_test.go
I'm working on integration [pgx](https://github.com/jackc/pgx) with Sentry. 
The new version of pgx provides an [interface](https://github.com/jackc/pgx/blob/master/tracer.go#L10) for tracing, which work in the way when you need to implement two different methods: TraceQueryStart & TraceQueryEnd.   
To implement `TraceQueryEnd`, I need to get access to span in context and call `Finish` on it.   
It would be great to provide a method to get span from context.   
Current workaround: 
```go
func SpanFromContext(ctx interface{}) (*sentry.Span, bool) {
values := reflect.ValueOf(ctx).Elem()
for i := 0; i < values.NumField(); i++ {
reflectValue := values.Field(i)
reflectValue = reflect.NewAt(reflectValue.Type(), unsafe.Pointer(reflectValue.UnsafeAddr())).Elem()
span, ok := …
```
> Expose SpanFromContext

- transport_test.go
> fix(test): Increase Flush timeout for TestKeepAlive test

- .github/workflows/test.yml
Windows builds are now sometimes taking more than 10 minutes :/
> fix(tests): Bump timeout to 15 minutes, update cache behavior

- otel/internal/utils/mapotelstatus.go
- otel/internal/utils/mapotelstatus_test.go
- otel/span_processor.go
> fix: OTel incorrect usage of attributes.Value.AsString resulting in an empty string for non-string values

- .github/workflows/test.yml
- Makefile
This merges `test` and `test-coverate` steps in CI - there's no point in running both as they do the same thing and it just adds waiting time for the CI to finish (especially on Windows).
> ci: merge test & test-coverage steps

- .github/workflows/lint.yml
- .github/workflows/test.yml
- CHANGELOG.md
- internal/traceparser/parser.go
- internal/traceparser/parser_test.go
- profiler_test.go
Run CI against Go 1.21
fix: profiler trace parsing code to accommodate changes
> ci: add go1.21

- .github/workflows/lint.yml
- .github/workflows/test.yml
- update cache action to v3 to support node16
- pin 3rd party actions to protect against attacks
Note: needs an update to settings to allow these actions.
> ci: update actions 

- _examples/profiling/main.go
- transport_test.go
Makes sure `wg.Done()` is called even if the test code in transport test fails. 
With the original code, a test failure in `testSendSignalEvent()` [would result in a timeout](https://github.com/getsentry/sentry-go/actions/runs/5855059551/job/15872114963) because `wg.Done()` was never called and thus the subsequent `wg.Fail()` would get blocked indefinitely.
In the new version, the actual test failure will be reported instead.
> test: fix hanging waitgroups

- transport_test.go
Transport `Flush()` test still fails even with the timeout increased recently in #663.
Let's go overboard here to 5 seconds in CI. I don't see any other way to make the test independent of timing...
> test: increase flush timeout in CI tests

- fasthttp/sentryfasthttp_test.go
- gin/sentrygin_test.go
- http/sentryhttp_test.go
- internal/testutils/consts.go
- logrus/logrusentry_test.go
- profiler_test.go
- transport_test.go
Follow up for #700 - I didn't notice there are multiple places we test the flush...
> test: deduplicate Flush() timeout settings

- CHANGELOG.md
- profile_sample.go
- profiler.go
- profiler_test.go
- profiler_windows.go
- traces_profiler.go
- traces_profiler_test.go
- tracing.go
- transport_test.go
Follow up on #626 - run a single profiler continuously (instead of a new profiler for each profiled transaction) and slice its data as needed. 
The `profileRecorder` starts when a first transaction would be sampled and then runs until the app is stopped.  I was thinking about starting/stopping when there's no transaction running but it would get more complicated and I'm not sure it's worth it because it would also make overall app performance less predictable (would differ when there's a transaction being profiled and when it's not). On the other hand, for very low sampling rate, it would be beneficial to only run when needed. In any case, the change to make the profiler start & pause on demand would be an incremental change that can be done in the future when the need arises (based on …
> Single profiler goroutine

- client.go
- client_test.go
- dsn.go
- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- gin/sentrygin.go
- http/sentryhttp.go
- iris/sentryiris.go
- logrus/logrusentry.go
- martini/sentrymartini.go
- negroni/sentrynegroni.go
- scripts/bump-version.sh
- sentry.go
- transport.go
- transport_test.go
> Set SDK Name According Framework being used

- helpers_test.go
- util.go
- util_test.go
_Builds from #652_
For information about this change, please read the referenced PR above.  This PR is building off of the previous one and adds tests for coverage.
> feat: Read release info from build info

- CHANGELOG.md
> doc: Prepare 0.24.0 release

- otel/span_processor.go
- otel/span_processor_test.go
Shutdown panics when passed a background context, or any context which doesn't contain a hub. Returning the current hub if no hub is found on the context prevents this.
Fixes #692
> fix(otel): prevent panic in shutdown

- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- gin/sentrygin.go
- http/sentryhttp.go
- iris/sentryiris.go
- martini/sentrymartini.go
- negroni/sentrynegroni.go
> fix: Guard against a nil client when setting the SDK identifer

- client.go
- client_test.go
- integrations.go
- integrations_test.go
Adds support for ignoring transactions by using the `IgnoreTransactions` client option. This requires a slice of regex strings that are matched against a transaction's name. If there's a match the transaction is dropped.
Fixes #628
> feat: support IgnoreTransactions client option

- client.go
- integrations.go
- integrations_test.go
Add global tags support.
Tags can be passed via client options or via environment variables by prefixing them with "SENTRY_TAGS_".
Setting scope tags overrides global tags.
Client option tags override environment variable tags.
Fixes: #331
> feat: global tags

- dsn.go
Based on customer feedback, we decided to keep this function for the time being.
I clarified when this function shall be used.
> Clarify the usage of `dsn.RequestHeaders()`

- sentry.go
This removes deprecated code before releasing version 0.25.0.
> Remove deprecated code

- CHANGELOG.md
Copy & Paste error, this was actually a breaking change.
I updated https://github.com/getsentry/sentry-go/releases/tag/v0.25.0 accordingly.
> Update changelog to mention Breaking Changes

- stacktrace.go
- stacktrace_below_go1.20.go
- stacktrace_below_go1.20_test.go
- stacktrace_go1.20.go
- stacktrace_go1.20_test.go
Go 1.20+ changed reserved prefixes for compiler-generated symbols from "go." and "type." to "go:" and "type:" respectively.
See: https://github.com/golang/go/commit/0f8dffd0aa71ed996d32e77701ac5ec0bc7cde01a
This adds support for both kinds of compiler-generated symbols depending on the Go version by taking advantage of build tags.
Fixes #180 
Inspired by and continued on from: https://github.com/getsentry/sentry-go/pull/707
> fix(stacktrace): support package name parsing for Go 1.20+

- span_recorder_test.go
- tracing.go
- tracing_test.go
Remove the SpanSampled, OpName, TransactionName, Transaction Source span options which are now deprecated and superseded by their "With" prefixed variants.
Fixes: #625
> ref: remove deprecated span options

- util.go
First check if the git command exists before attempting to execute it. This ensures that we don't trigger any unwanted side effects, such as triggering a xcode cli tools install on macs.
> fix(util): check if git command exists when setting release

- internal/testutils/notrace.go
- internal/testutils/race.go
- profiler_test.go
Some tests are flaky if the machine is overloaded - some goroutines may not get captured consistently on all ticks. And since we cannot control the number of goroutines running (HTTP workers from other tests hang around indefinitely, see https://github.com/getsentry/sentry-go/issues/731). Disabling the flaky test in CI when race detection is on. We can enable it once #731 is fixed.
The other flaky test I'm not sure about so just adding logs and maybe it would hep figure out what's wrong:
```
--- FAIL: TestProfilerPanicOnTick (0.00s)
profiler_test.go:339: 
Error Trace:	/home/runner/work/sentry-go/sentry-go/profiler_test.go:339
/home/runner/work/sentry-go/sentry-go/profiler_test.go:263
Error:      	Should NOT be empty, but was 
Test:       	TestProfilerPanicOnTick
```
> ci: improve flaky tests

- tracing.go
- tracing_test.go
Instead we rely on a new implementation of IsTransaction() that checks if the span's parent is nil.
Fixes #581
> ref: remove Span.isTransaction attribute

- propagation_context.go
- propagation_context_test.go
- scope.go
- scope_concurrency_test.go
- scope_test.go
This is the start of a series of PRs for implementing tracing without performance.
This initial PR adds a `PropagationContext` field to the scope.
> feat(tracing without performance): add propagation context to scope

- tracing.go
- tracing_test.go
This pull request adds `WithDescription` span option! Closes #739, thank you to @moneymikemd for the issue.
- Disclaimer: I was just diving into the go SDK codebase, and was looking through the issue list for an easy way in. Please feel free to tell me to gtfo if that pull request is not all that useful. 
- I've added the `WithDescription` `SpanOption` that works similar to the existing `WithTransactionName` and friends.
/cc @greywolve
> feat(tracing): Add WithDescription SpanOption

- scope.go
- scope_concurrency_test.go
- scope_test.go
This is part of a series of PRs for the "tracing without performance" feature.
For the case where performance is enabled we need to be able to get the tracing context from the active transaction and use that instead of the propagation context. So we need to way to access the span. 
This PR adds support for setting a span on a scope. We can then access the span and get the current tracing context to pass through.
> feat(tracing without performance): set span on scope

- client.go
- interfaces.go
We should only sample errors/messages. This fixes the `SampleRate` being applied to `check_in` as well.
> Only apply `SampleRate ` to errors/messages

- interfaces.go
Closes https://github.com/getsentry/sentry-go/issues/767
> Fix `Exception.ThreadID` type

- otel/span_processor.go
- otel/span_processor_test.go
- tracing.go
- tracing_test.go
> fix(otel): allow other data types for span data values

- echo/sentryecho_test.go
Wanted to resolve #97. Are any other tests required to close it?
It's only missing martini (very outdated, not sure if anyone still uses it) and Iris. For Iris tests should be identical to Echo.
> Add tests for echo

- README.md
- echo/README.md
- fasthttp/README.md
- gin/README.md
- http/README.md
- iris/README.md
- martini/README.md
- negroni/README.md
Updated all godoc.org links to pkg.go.dev, as they are already redirected anyway.
> Replace godoc links with pkg.go.dev

- interfaces.go
Replaced bool with empty struct to better represent a set, which is what SensitiveHeaders is.
```
func BenchmarkNewRequest(b *testing.B) {
const payload = `{"test_data": true}`
r := httptest.NewRequest("POST", "/test/?q=sentry", strings.NewReader(payload))
r.Header.Add("Authorization", "Bearer 1234567890")
r.Header.Add("Cookie", "foo=bar")
r.Header.Add("X-Forwarded-For", "127.0.0.1")
r.Header.Add("X-Real-Ip", "127.0.0.1")
r.Header.Add("Some-Header", "some-header value")
b.ReportAllocs()
for i := 0; i < b.N; i++ {
NewRequest(r)
}
}
```
**Before:**
```
BenchmarkNewRequest-10    	 2724643	       430.9 ns/op	     504 B/op	       7 allocs/op
```
**After:**
```
BenchmarkNewRequest-10    	 2993946	       394.1 ns/op	     504 B/op	       7 allocs/op
```
> Use set for sensitiveHeaders

- dsn.go
- interfaces.go
- internal/ratelimit/category.go
- sentry.go
- traces_profiler.go
- tracing.go
Was browsing through code and made some minor improvements.
> minor improvements

- .craft.yml
- .github/workflows/danger.yml
- CHANGELOG.md
I never liked this workflow, as it decreases the quality of the changelog and nags people willing to contribute.
> Revert "ci: add the common Danger workflow (#799)"

- client_test.go
- interfaces.go
- interfaces_test.go
- logrus/logrusentry_test.go
- util.go
- util_test.go
While updating `develop` for [#1204](https://github.com/getsentry/develop/issues/1204), noticed that the new mechanism fields were at the wrong place.
[RFC 0079](https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md#new-mechanism-fields) specifies these fields (is_exception_group, parent_id, exception_id) to be in the mechanism.
This is how I initially implemented it, but for some reason (UI being broken?) I moved them to Data which is wrong according to RFC and other SDKs.
This is how it looks like on the UI.
> Move exception group fields to mechanism

- echo/sentryecho_test.go
Not that important, a nitpick, but aligning with the ubiquitous GetSpan instead of GetTransaction, since Michi told me that GetTransaction should guarantee that the user will the root transaction (in which we can't).
> chore(echo): rename GetTransaction to GetSpan

- interfaces.go
- traces_profiler.go
- traces_profiler_test.go
Perhaps we should also do type checks?
> Fix setting of tracing variables

- negroni/sentrynegroni.go
- negroni/sentrynegroni_test.go
Addresses #496
Tests will come at a later time (on this PR), probably next weekend.
> feat(negroni): performance tracing

- echo/sentryecho.go
- echo/sentryecho_test.go
- fasthttp/sentryfasthttp.go
- fasthttp/sentryfasthttp_test.go
- gin/sentrygin.go
- gin/sentrygin_test.go
- http/sentryhttp.go
- http/sentryhttp_test.go
This PR adds:
http method/response code to Echo and net/http
http response code to fasthttp and gin
Adds transaction tests for net/http
Once other integrations are covered in #809, #808 and #807 - all of them should have `http.response.status_code` which I would assume would resolve #667 .
> Normalize http.response.status_code

- check_in.go
- client_test.go
https://github.com/getsentry/team-sdks/issues/43
https://develop.sentry.dev/sdk/check-ins/
> Add`FailureIssueThreshold` & `RecoveryThreshold` to MonitorConfig

- client_test.go
- integrations.go
- integrations_test.go
> Match on strings for `ignoreErrors` & `ignoreTransactions`

- transport.go
- transport_test.go
This will let us pass a context.Context when creating a new request with getRequestFromEvent.
This will let us have a more granular control over how/when we cancel a request instead of relying only on the client timeout.
For example, if such API is invoked while serving another HTTP request, we might want to take advantage of such request context to bail out earlier than the client timeout if necessary.
As per [documentation](https://pkg.go.dev/net/http#Request.Context):
> For outgoing client requests, the context controls cancellation.
> 
> For incoming server requests, the context is canceled when the client's connection closes, the request is canceled (with HTTP/2), or when the ServeHTTP method returns.
> add SendEventWithContext method

- transport.go
https://github.com/getsentry/sentry-go/pull/824 introduced changes resulting in the lint CI checks failing.
> Fix go lint issues

- echo/sentryecho.go
- fasthttp/sentryfasthttp.go
- fiber/sentryfiber.go
- gin/sentrygin.go
- http/sentryhttp.go
- iris/sentryiris.go
- negroni/sentrynegroni.go
- tracing.go
- tracing_test.go
> Add trace origin

- .github/workflows/test.yml
- CHANGELOG.md
- client.go
- stacktrace.go
- stacktrace_test.go
I don't find this solution elegant in particular, but it adds ability to skipFrames in StackTrace (which resolves #741 for example).
Is EventFromMessage invoked directly by external users? If so, this would be a breaking change and instead a variadic options/parameter could be added.
I'll add tests once we agree on the implementation.
> Add ability to skip frames

- tracing.go
- tracing_test.go
Fix StartTransaction to update current transaction context before returning it
> Closes #854

- interfaces.go
- interfaces_test.go
> feat(request): Add Proxy-Authorization as a sensitive header

- .github/workflows/test.yml
We advertise support for the latest 3 Go versions in the README, but this puts us at testing the latest 6 - maybe we can consider trimming some of the older versions.
> ci: add go1.23

- CHANGELOG.md
- stacktrace.go
- stacktrace_below_go1.21.go
- stacktrace_below_go1.21_test.go
- stacktrace_go1.21.go
- stacktrace_go1.21_test.go
Resolves #712 
An alternative is not to have build tags for this, but that means it'll traverse the frames without purpose on Go <1.21.
> Function grouping prefix fix

- client.go
- stacktrace.go
- stacktrace_test.go
This reverts commit d95747f906d86bace950fc8eb5a7605a1e1dbc64.
This didn't turn out really useful, we need to find a better way.
> Revert "Add ability to skip frames (#852)"

- scope.go
- tracing.go
Fixes https://github.com/getsentry/sentry-go/issues/884
We mistakenly used the scope's span `trace` context as the `trace` context for the transaction. Instead, we now set the `trace` context on the event when the transaction finishes and only use the scope's span `trace` context in case there is no `trace` context on the event already.
> Fix applying the `trace` context on events

- tracing.go
- tracing_test.go
Problem:
Previously, when creating a chain of spans, events triggered with the sentry.CaptureMessage() could be associated with the wrong span due to using the incorrect span in the hub’s scope, which led to inaccurate trace data in Sentry.
Fix:
By introducing proper span scope management, each non-transaction span now pushes a scope when started and pops it when finished. This ensures that events are associated with the correct active span in the trace hierarchy. Transactions remain unchanged as the root elements.
Test Coverage:
The new TestSpanScopeManagement confirms that events captured after finishing a child span are correctly associated with that span, ensuring that the trace and span IDs are accurate.
> Fix scope management in StartSpan and doFinish

- CHANGELOG.md
- client_test.go
- interfaces.go
- interfaces_test.go
- logrus/logrusentry_test.go
> Set mechanism type to generic

- logrus/README.md
I noticed that README is missing in logging integrations (rest of them have it). If the format is fine, I'll create it for zerolog and slog as well.
> add readme for logrus integration

- CHANGELOG.md
- fasthttp/sentryfasthttp.go
- fiber/sentryfiber.go
Resolves #911 
If r.URL is not set due to some error, setting r.URL.RawQuery panics. Panic is recovered, but `request` is never converted thus causing another panic.
> Prevent panic in case url.Parsing fails in fasthttp and fiber

- CHANGELOG.md
- dynamic_sampling_context_test.go
- interfaces.go
- interfaces_test.go
- scope_test.go
- slog/converter.go
- slog/converter_test.go
ref https://github.com/getsentry/team-sdks/issues/44
Remove user segment and all user segment related logic.
https://go.dev/ref/mod#go-mod-file-module-deprecation
> feat: Remove user segment

- CHANGELOG.md
- logrus/logrusentry.go
- logrus/logrusentry_test.go
> Add HubProvider functionality for logrus integration

- logrus/go.mod
Fixes https://github.com/getsentry/sentry-go/issues/949.
> Rename sentry-go/logrus module

- .github/workflows/lint.yml
Don't think we need this here.
> Remove github token in lint

- go.mod
- go.sum
Update github.com/stretchr/testify to v1.8.4 to remove circular dependency on github.com/stretchr/objx
> chore(deps): update github.com/stretchr/testify to v1.8.4

- attribute/builder_test.go
- attribute/bulider.go
- attribute/rawhelpers.go
- attribute/value.go
- attribute/value_test.go
Implement the attributes API for typesafe values to set on spans.
```go
// creating [attribute.Values]
strValue := attribute.StringValue("value")
intValue := attribute.IntValue(42)
int64Value := attribute.Int64Value(42)
float64Value := attribute.Float64Value(42.1)
// accessing them
strValue.AsString()
intValue.AsInt64()
// creating [attribute.Builder]
attribute.String("key", "value")
attribute.Int("key.int", 42)
// usage example with SetData 
span.SetData("key",  attribute.StringValue("value"))
```
allow `SetData` to handle a `map[string]Value` for providing easier access to the span values and also ensure that we support all values provided on `SetData`. An example of how that would look like is something like:
```go
span.SetData(
attribute.String("key", "value"), …
```
> Add attributes API

- _examples/http/main.go
- client.go
- fasthttp/sentryfasthttp.go
- fiber/sentryfiber.go
- hub.go
- integrations.go
- scope.go
- span_recorder.go
- span_recorder_test.go
- tracing.go
- transport.go
- util.go
renaming the debug logger to DebugLogger so that we can define the Logger interface for implementing logs in our SDK.
> Rename Logger to DebugLogger

- log.go
- log_test.go
Closes #1017 .
When `SendDefaultPII` is enabled, we should be adding user details on the logs payload.
> Add user details when DefaultPII is enabled

- tracing.go
- tracing_test.go
Fix `ContinueFromHeaders` so that the DSC is unfrozen when `sentry-trace` is missing and `baggage` is present.
Closes #1025 (GO-52).
> Fix continue from trace when sentry-trace does not exist

- interfaces.go
- log.go
Quick fix for changing the LogLevel signature to properly use `LogLevel` instead of the event `Level`.
> fix: use correct Level signature for logs

- log.go
- log_test.go
According to the docs here https://develop.sentry.dev/sdk/telemetry/logs/#sdk-integration-attributes, `sentry.origin` should only be set for integrations.
> Fix remove sentry.origin for sentry logger

- logrus/logrusentry.go
- logrus/logrusentry_test.go
We should handle everything a user sets as attributes on logs. 
- The user attributes should be handled by the default log if set on the scope.
- The other keys should be passed as is.
> Remove handling for specific logrus keys

- scope.go
- transport.go
- transport_test.go
Partial fix for #1047.
- Fixing a race condition on GetSpan by adding a mutex.
- Guarding transport so that you can only close the `done` channel once, to avoid panics.
> Fix race condition on GetSpan and guard transport Close

- interfaces.go
- marshal_test.go
- testdata/json/checkin/003.json
The checkInMarshalJSON function was missing FailureIssueThreshold and RecoveryThreshold fields when serializing MonitorConfig, causing these values to be omitted from the JSON payload sent to Sentry's API. This results in Sentry using default values instead of the configured values.
This adds the missing fields to the JSON serialization and includes a regression test to prevent future occurrences.
**Root Cause:**
- `checkInMarshalJSON` in `interfaces.go` was not including FailureIssueThreshold and RecoveryThreshold fields
- These fields were never sent to Sentry's API, regardless of SDK configuration
- Sentry defaults to FailureIssueThreshold=1 and RecoveryThreshold=1 when not provided
**Changes:**
- Fixed `checkInMarshalJSON` in `interfaces.go` to include missing fields in JSON payload
- …
> Fix missing FailureIssueThreshold and RecoveryThreshold in MonitorConfig JSON serialization

- _examples/logs/main.go
- interfaces.go
- log.go
- log_fallback.go
- log_test.go
- logrus/logrusentry.go
- logrus/logrusentry_test.go
- slog/converter.go
- slog/sentryslog.go
Closes #1042. See issue for more details.
Modifying existing API to make usage clearer. Introducing chaining of attributes:
- Multiple levels `Trace`, `Debug`, `Info`, `Warn`, `Error`, `Panic`, `Fatal` that return a `LogEntry`
- Attribute API on each `LogEntry`, to set `String`, `Int`, ...
- WithCtx func to inject context to entry
- Emit & Emitf functions to create a message and send the log
Example:
```go
loggerWithVersion := sentry.NewLogger(ctx)
// Setting  attributes (these persist across log calls)
loggerWithVersion.SetAttributes(
attribute.String("permanent.version", "1.0.0"),
)
// Add attributes to log entry
loggerWithVersion.Info().WithCtx(ctx).
String("key.string", "value").
Int("key.int", 42).
Bool("key.bool", true).
// don't forget to call Emit to send the logs to Sentry …
```
> Modify log API

- log.go
- log_race_test.go
- log_test.go
Closes both #1048  and #1049.
Adds tests for the logger to identify race conditions and fix everything uncovered.
Changes include: 
* Add locks when using `SetAttributes` to guard for panics.
* Lock scope when trying to access propagation context on `log`.
> Fix race conditions on log when accessing scope

- client.go
- client_test.go
- log_race_test.go
- transport.go
- transport_test.go
This aims to fix flakiness of `TestHTTPTransportDoesntLeakGoroutines`. The test would report goroutines stuck in network I/O operations, where the `http.DefaultClient` would hang and then the `goleak.VerifyNone` would incorrectly spot them as leaked goroutines on the transport. The solution is adding a `mockTransport` to each test client we create on the tests. 
In addition also added a small fix that might also cause goroutine issues. When using the `time.After` func, a goroutine would be spawned. Using `ctx.Done()` eliminates the goroutine and also improves readability.
> Fix flaky tests

- interfaces.go
- interfaces_test.go
- internal/ratelimit/category.go
- internal/ratelimit/category_test.go
- internal/ratelimit/rate_limits_test.go
- transport.go
Closes #1081. 
Properly handle rate limits by:
- Add missing types for Logs and CheckIns. 
- Add CategoryUnknown to enum for debugging purposes. Unknown categories should not get rate limited.
- Tidy: move category transformation to Event.
> add missing rate limit categories

- .github/workflows/test.yml
- Makefile
- echo/go.mod
- fasthttp/go.mod
- fiber/go.mod
- gin/go.mod
- go.mod
- iris/go.mod
- logrus/go.mod
- negroni/go.mod
- otel/go.mod
- slog/go.mod
- zerolog/go.mod
Once merged, update the Required Status checks to include the newly added Go 1.25 checks. Go 1.22 was already removed to being able to merge this one.
> Run tests on Go 1.25 and remove Go 1.22

- client.go
- fasthttp/sentryfasthttp.go
- fiber/sentryfiber.go
- hub.go
- integrations.go
- internal/debuglog/log.go
- internal/debuglog/log_test.go
- log.go
- log_fallback.go
- log_test.go
- logrus/logrusentry.go
- scope.go
- slog/converter.go
- span_recorder.go
- span_recorder_test.go
- tracing.go
- transport.go
- util.go
Create a `debuglog` package to easily access the `sentry.DebugLogger` without depending on the root level. This change aims to remove any cyclic imports when internal packages are used on the top level, but also want to access the debug logger. 
* resolves: #1104 
* resolves: GO-88
> ref: create debuglog package
